---
# role: ansible-role-kickstart
# file: tasks/create.yml

- name: "Create kickstart file {{ kickstart_hostpath }}"
  become: false
  delegate_to: "{{ kickstart_host }}"
  ansible.builtin.template:
    src: kickstart.cfg.j2
    dest: "{{ kickstart_hostpath }}"
    mode: 0660
    validate: ksvalidator --version={{ kickstart_version }} %s
