---
# role: ansible-role-kickstart
# file: tasks/main.yml

- name: "Install pykickstart on kickstart host"
  ansible.builtin.include_tasks: install.yml
  when: inventory_hostname == kickstart_host

- name: "Create kickstart file"
  ansible.builtin.include_tasks: create.yml
  when: kickstart_template is defined
