---
# code: language=ansible
# role: jam82.kickstart
# file: tasks/main.yml

- name: "Install pykickstart"
  become: true
  ansible.builtin.dnf:
    name: pykickstart
    state: present

- name: "Create kickstart file"
  become: false
  ansible.builtin.template:
    src: kickstart.cfg.j2
    dest: "{{ item.dest }}"
    mode: '0660'
    validate: ksvalidator --version={{ item.version }} %s
  loop: "{{ kickstart_files }}"
