---
# code: language=ansible
# role: jomrr.kickstart
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: meta/requirements.yml
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: fedora-kickstart
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    command: null
    entrypoint: null
    systemd: true
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
verifier:
  name: ansible
