---
# code: language=ansible
# role: jam82.kickstart
# file: molecule/resources/playbooks/converge.yml

- name: "PLAYBOOK | Converge"
  hosts: all
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
