---
# role: ansible-role-kickstart
# file: molecule/resources/playbooks/prepare.yml

- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: "Update dnf cache"
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_pkg_mgr == "dnf"

    - name: "Update yum cache"
      ansible.builtin.yum:
        update_cache: true
      when: ansible_pkg_mgr == "yum"

    - name: "Update zypper cache"
      community.general.zypper:
        name: sudo
        update_cache: true
      when: ansible_pkg_mgr == "zypper"
