---
# code: language=ansible
# role: jomrr.kickstart
# file: molecule/resources/playbooks/verify.yml

- name: "PLAYBOOK | Verify"
  hosts: all
  gather_facts: false
  tasks:
    - name: "Assertions"
      ansible.builtin.assert:
        that: true
