---
# role: ansible-role-kickstart
# file: molecule/tox/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: kickstart-${TOX_ENVNAME:-"default"}
    image: "${uns:-jam82}/molecule-${img:-fedora}:${tag:-latest}"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        kickstart_role_enabled: true
verifier:
  name: ansible
